# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(0b53145a-fe19-4ae8-b3ab-e6ee5b82c98e)'
    appType: 'webAppLinux'
    appName: 'testing-deployments-api'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'